name: GitHub Push Notifications to Slack

on:
  schedule:
    # Run every hour to check for new pushes
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual triggering

# No environment variables needed - repositories are defined in .github/config/monitored-repos.json

jobs:
  notify-pushes:
    name: Check for new pushes and notify Slack
    runs-on: blacksmith-8vcpu-ubuntu-2204
    timeout-minutes: 10

    steps:
      - name: Checkout infrastructure repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Claude Code SDK
        run: |
          pip install claude-code-sdk

      - name: Validate secrets
        run: |
          if [ -z "${{ secrets.ANTHROPIC_API_KEY }}" ]; then
            echo "::error::ANTHROPIC_API_KEY secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.SLACK_WEBHOOK_URL }}" ]; then
            echo "::error::SLACK_WEBHOOK_URL secret is not set"
            exit 1
          fi

      - name: Process repository pushes
        uses: actions/github-script@v7
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          script: |
            const script = await import('./.github/scripts/process-pushes.js')
            await script.default({github, context, core})